import AUGMENTED from './AUGMENTED';
import DIMINISHED from './DIMINISHED';
import MAJOR_SEVENTH from './MAJOR_SEVENTH';
import MAJOR from './MAJOR';
import MINOR_MAJOR_SEVENTH from './MINOR_MAJOR_SEVENTH';
import MINOR_SEVENTH from './MINOR_SEVENTH';
import MINOR from './MINOR';
import SEVENTH from './SEVENTH';

export default {
  AUGMENTED,
  DIMINISHED,
  MAJOR_SEVENTH,
  MAJOR,
  MINOR_MAJOR_SEVENTH,
  MINOR_SEVENTH,
  MINOR,
  SEVENTH
};
