import CHROMATIC from './CHROMATIC';
import MAJOR from './MAJOR';
import NATURAL_MINOR from './NATURAL_MINOR';
import HARMONIC_MINOR from './HARMONIC_MINOR';

import MAJOR_PENTATONIC from './MAJOR_PENTATONIC';
import MINOR_PENTATONIC from './MINOR_PENTATONIC';

export default {
  CHROMATIC,
  MAJOR,
  NATURAL_MINOR,
  HARMONIC_MINOR,
  MAJOR_PENTATONIC,
  MINOR_PENTATONIC
};
