// https://en.wikipedia.org/wiki/Interval_(music)#Interval_number_and_quality

export default {
  DIMINISHED_SECOND: 0,
  AUGMENTED_UNISON: 1,
  DIMISHED_THIRD: 2,
  AUGMENTED_SECOND: 3,
  DIMINISHED_FOURTH: 4,
  AUGMENTED_THIRD: 5,
  DIMINISHED_FIFTH: 6,
  AUGMENTED_FOURTH: 6, // 2 POSSIBLE
  DIMINISHED_SIXTH: 7,
  AUGMENTED_FIFTH: 8,
  DIMINISHED_SEVENTH: 9,
  AUGMENTED_SIXTH: 10,
  DIMINISHED_OCTAVE: 11,
  AUGMENTED_SEVENTH: 12
};
